id: ha
label: High Availability
type: architecture
description: >-
  Clusters configured for high availability with multiple control-plane nodes,
  where uptime and resilience are primary concerns.
items:
  required:
    - CLUD-11
    - CLST-12
    - CLST-14
    - CLST-15
    - CLST-16
    - CONT-8
    - CONT-10
    - CONT-12
    - CONT-13
    - CONT-14
    - CODE-008
  suggested:
    - CLUD-8
    - CLST-6
