id: hipaa
label: HIPAA
type: compliance
description: >-
  Controls required to support HIPAA compliance for workloads that store,
  process, or transmit Protected Health Information (PHI).
items:
  required:
    - CLUD-7
    - CLUD-9
    - CLST-6
    - CLST-11
    - CLST-18
    - CLST-46
    - CONT-3
    - CONT-7
    - CODE-003
    - CODE-007
  suggested:
    - CLUD-2
    - CLUD-3
    - CLST-10
    - CLST-15
    - CONT-9
    - CONT-11
    - CONT-12
    - CONT-21
    - CODE-002
    - CODE-005
