id: pci-dss
label: PCI-DSS v4.0
type: compliance
description: >-
  Controls mapped to PCI-DSS v4.0 requirements for clusters that process, store,
  or transmit cardholder data or are in scope of the Cardholder Data Environment
  (CDE).
items:
  required:
    - CLUD-1
    - CLUD-2
    - CLUD-7
    - CLST-1
    - CLST-2
    - CLST-5
    - CLST-6
    - CLST-11
    - CLST-12
    - CLST-18
    - CLST-46
    - CLST-31
    - CONT-2
    - CONT-3
    - CONT-4
    - CONT-7
    - CONT-8
    - CONT-9
    - CONT-21
    - CODE-001
    - CODE-002
    - CODE-004
    - CODE-007
  suggested:
    - CLUD-4
    - CLUD-5
    - CODE-005
    - CODE-006
