id: baseline
label: General Baseline
type: baseline
description: >-
  Core security and operational items recommended for every Kubernetes cluster,
  regardless of provider or environment.
items:
  required:
    - CLST-1
    - CLST-2
    - CLST-3
    - CLST-5
    - CLST-6
    - CLST-8
    - CLST-9
    - CLST-11
    - CLST-12
    - CLST-17
    - CLST-31
    - CLST-32
    - CLST-39
    - CLST-47
    - CLST-51
    - CONT-2
    - CONT-3
    - CONT-4
    - CONT-7
    - CONT-8
    - CONT-10
    - CONT-21
    - CONT-25
    - CONT-26
    - CONT-27
    - CONT-28
    - CODE-13
    - CODE-22

  suggested:
    - CLUD-1
    - CLUD-2
    - CLUD-9
    - CLUD-11
    - CLUD-23
    - CLST-10
    - CLST-13
    - CLST-16
    - CLST-18
    - CLST-21
    - CLST-22
    - CLST-29
    - CLST-30
    - CLST-34
    - CLST-38
    - CLST-45
    - CLST-49
    - CLST-50
    - CLST-52
    - CLST-53
    - CLST-54
    - CLST-55
    - CLST-56
    - CLST-57
    - CLST-58
    - CONT-5
    - CONT-6
    - CONT-11
    - CONT-12
    - CONT-13
    - CONT-14
    - CONT-15
    - CONT-16
    - CONT-17
    - CONT-18
    - CONT-19
    - CONT-23
    - CONT-24
    - CONT-29
    - CONT-31
    - CONT-32
    - CODE-3
    - CODE-8
    - CODE-14
    - CODE-16
    - CODE-17
    - CODE-18
