id: hipaa
label: HIPAA
type: compliance
description: >-
  Controls required to support HIPAA compliance for workloads that store,
  process, or transmit Protected Health Information (PHI).
items:
  required:
    - CLUD-7
    - CLUD-9
    - CLST-6
    - CLST-11
    - CLST-18
    - CLST-31
    - CLST-32
    - CLST-46
    - CONT-3
    - CONT-7
    - CONT-32
    - CODE-3
    - CODE-7
  suggested:
    - CLUD-2
    - CLUD-3
    - CLST-10
    - CLST-15
    - CLST-38
    - CLST-54
    - CLST-57
    - CLST-58
    - CLST-59
    - CLST-60
    - CONT-9
    - CONT-11
    - CONT-12
    - CONT-13
    - CONT-21
    - CONT-29
    - CODE-2
    - CODE-5
    - CODE-17
